services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    platform: linux/amd64
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=4534
    volumes:
      - ./config:/config
      - /mnt/external_storage/Torrents:/downloads
    ports:
      - 4534:4534
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
